ALTER TABLE planets ADD COLUMN rotation_axis_x REAL NOT NULL DEFAULT 0.0;
ALTER TABLE planets ADD COLUMN rotation_axis_y REAL NOT NULL DEFAULT 1.0;
ALTER TABLE planets ADD COLUMN rotation_axis_z REAL NOT NULL DEFAULT 0.0;
ALTER TABLE planets ADD COLUMN rotation_speed REAL NOT NULL DEFAULT 10.0;
